"""create links table

Revision ID: 904df92b74c4
Revises: 
Create Date: 2025-01-30 14:47:59.357749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "904df92b74c4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("full_url", sa.String(), nullable=False),
        sa.Column("short_url", sa.String(), nullable=True),
        sa.Column("count_requests", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("links_pkey")),
        sa.UniqueConstraint("full_url", name=op.f("links_full_url_key")),
        sa.UniqueConstraint("short_url", name=op.f("links_short_url_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
